 # rosi simulation parameters
 sim_rosi:

   sim_config:

     # Simulation rendering
     # turn it off to disable simulation visualization rendering
     sim_rendering: false

     # Velodyne processing flag
     # enable it for generating Velodyne data
     # disable it for faster simulation (but no Velodyne data)
     # possible values: true, false.
     velodyne_processing: false

     # Kinect processing flag
     # enable it for generating kinect data
     # disable it for faster simulation (but no kinect data)
     # possible values: true, false.
     kinect_processing: false

     # Hokuyo processing flag
     # enable it for generating Hokuyo data
     # disable it for faster simulation (but no hokuyo data)
     # possible values: true, false.
     hokuyo_processing: false

     # Camera on the manipulator tool processing flag
     # enable it for processing/publishing the manipulator tool cam
     # possible values: true, false
     manipulator_toolCam_processing: false


